MarkPro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bookmarks.views import (
    homeview,
    newsView,
    newsDetailView,
    newsListView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bookmarks.urls', namespace="bookmarks")),

]

bookmarks/urls.py
from django.conf.urls import url
from .views import *

urlpatterns= [
    url(r'^$', homeview , name="index"),
    url(r'^login/$', loginView , name="login_user"),
    url(r'^logout_user/$', logoutView, name='logout_user'),
    url(r'^register/$', registerView , name="register"),

    #collections
    url(r'^collections/$', collectionView , name="collections"),
    url(r'^collections/create/$', create_collection, name="create_collections"),
    url(r'^collections/(?P<id>[\w-]+)/update/$', update_collection.as_view(), name="update_collections"),
    url(r'^collections/(?P<slug>[\w-]+)/delete/$', delete_collection.as_view(), name="delete_collection"),
    url(r'^collections/(?P<slug>[\w-]+)/$', collectionDetailView.as_view(), name="collection_detail"),


    #bookmarks
    url(r'^(?P<collection_id>[0-9]+)/create_bookmarks/$', create_bookmarks, name='create-bookmark'),
    url(r'^(?P<pk>[0-9]+)/delete_bookmark/$', delete_bookmark.as_view(),name="delete-bookmark"),
    #news
    url(r'^news/$',newsView, name="news"),
    # url(r'^news/$',newsListView.as_view(), name="news"),
    url(r'^news/(?P<slug>[\w-]+)/$', newsDetailView.as_view(), name="news_detail"),
    # url(r'^news/(?P<news>\w+)/$$',newsDetailView.as_view(), name="news"),

]

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.core.validators import URLValidator

from django.core.urlresolvers import reverse

def rl_pre_save_receiver(sender, instance, *args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

class Newsboard(models.Model):
    title = models.CharField(max_length = 255)
    topic = models.CharField(max_length= 255)
    description = models.TextField()
    timestamp= models.DateTimeField(auto_now=False, auto_now_add=True)
    updated= models.DateTimeField(auto_now=True, auto_now_add=False)
    slug= models.SlugField(null=True, blank=True)
    def __str__(self):
        return self.title


pre_save.connect(rl_pre_save_receiver, sender=Newsboard)

class Collection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    list_title=models.CharField(max_length=200)
    list_type=models.CharField(max_length=200)
    list_description=models.TextField()
    collection_logo = models.FileField(blank=True, null=True)
    timestamp= models.DateTimeField(auto_now=False, auto_now_add=True)
    updated= models.DateTimeField(auto_now=True, auto_now_add=False)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.list_title
    # def __iter__(self):
    #     return iter(self._values)
        # return [field.value_to_string(self) for field in Collection._meta.fields]
    def get_absolute_url(self, *args, **kwargs):
        return reverse('bookmarks:collection_detail', kwargs={'pk': self.pk })


pre_save.connect(rl_pre_save_receiver, sender=Collection)

class Bookmarks(models.Model):

    collection =models.ForeignKey(Collection, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    bookmarks_links= models.TextField(validators=[URLValidator()])
    bookmarks_description= models.TextField()

    def __str__(self):
        return self.name


"""
Add timestamp and modified time.
Source over here
https://stackoverflow.com/questions/1737017/django-auto-now-and-auto-now-add
---------------------------------------
I would recommend not using auto_now or auto_now_add and
instead define your own save() method to make sure that created is only updated if id is not set 
(such as when the item is first created), 
and have it update modified every time the item is saved.
from django.utils import timezone

class User(models.Model):
    created     = models.DateTimeField(editable=False)
    modified    = models.DateTimeField()

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(User, self).save(*args, **kwargs)

"""

bookmarks/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Collection, Newsboard, Bookmarks


class CollectionForm(forms.ModelForm):
    class Meta:
        model= Collection
        fields=['list_title', 'list_type', 'list_description']

class BookmarkForm(forms.ModelForm):
    class Meta:
        model= Bookmarks
        fields= ['name', 'bookmarks_links', 'bookmarks_description']

class NewsboardForm(forms.ModelForm):
    class Meta:
        model= Newsboard
        fields= '__all__'


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model= User
        fields = ['username', 'password', 'email']



bookmarks/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout, authenticate, login
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView,DeleteView, UpdateView
from django.db.models import Q
from django.urls import reverse_lazy
from .models import Newsboard, Collection, Bookmarks
from .forms import LoginForm, CollectionForm, NewsboardForm, BookmarkForm
from django.http import HttpResponseRedirect

def homeview(request):
    #HomeTemplateView
    if not request.user.is_authenticated():
        template_name = 'bookmarks/home_visitor.html'
    else:
        template_name = 'bookmarks/home.html'
    story = Newsboard.objects.all().order_by('-timestamp')
    context = {
        "newsboard": story
    }
    return render(request, template_name, context)

def newsView(request):
    template_name = "bookmarks/news.html"
    story = Newsboard.objects.all().order_by('-timestamp')
    context = {
        "newsboard": story
    }
    return render(request, template_name, context)

class newsListView(ListView):
    """
        Same as newsView(request)
        ListView to display news with filter

    """
    queryset= Newsboard.objects.all()
    template_name = "bookmarks/news.html"
    def get_queryset(self):
        slug = self.kwargs.get("slug")
        if slug:
            queryset=Newsboard.objects.filter(
                Q(topic__iexact=slug) |
                Q(topic__icontains=slug)
            )
        else:
            queryset=Newsboard.objects.all()
        return queryset

class newsDetailView(DetailView):

    queryset= Newsboard.objects.all()
    # def get_context_data(self, *args, **kwargs):
    #     print(self.kwargs)
    #     #get the id
    #     context= super(newsDetailView,self).get_context_data(*args, **kwargs)
    #     print(context)
    #     # it returns the object details
    #     return context

    # def get_object(self, *args, **kwargs):
    #     """
    #         This function is to change the urls.py as news_id
    #         pk  >  news_id
    #         url(r'^news/(?P<news_id>\w+)/$$', newsDetailView.as_view(), name="news"),
    #         if not will get AttributeError. Must be pk or slug.
    #         This function is not necessary if you stay as pk or slug.
    #     """
    #     news_id= self.kwargs.get('news_id')
    #     obj=get_object_or_404(Newsboard, id=news_id)
    #     return obj


def loginView(request):
    if request.method == "POST":
        username= request.POST['username']
        password= request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                if not request.user.is_authenticated():
                    template_name = 'bookmarks/home_visitor.html'
                else:
                    template_name = 'bookmarks/home.html'
                story = Newsboard.objects.all().order_by('-timestamp')
                context = {
                    "Newsboard": story
                }
                return render(request, template_name, context)

            else:
                return render(request, 'bookmarks/login/login.html',{'error_message': 'Your account has been disabled'})
        else:
            return render(request,'bookmarks/login/login.html', {'error_message': 'Invalid Login'})
    return render(request, 'bookmarks/login/login.html')

def logoutView(request):
    logout(request)
    form = LoginForm(request.POST or None)
    return render(request, 'bookmarks/login/login.html',{'form': form })

def registerView(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('/')
                #does not change url
                # return render(request, 'bookmarks/home.html', { 'user': request.user } )

    return render(request, 'bookmarks/login/register.html', {'form': form})



def collectionView(request):
    if not request.user.is_authenticated():
        return render(request, 'bookmarks/login/login.html')
    else:
        collections = Collection.objects.filter(user=request.user)
        return render(request, 'bookmarks/collections.html', {'collections': collections})

class collectionDetailView(DetailView):
    #default template name is myModelName_detail.html
    template_name = 'bookmarks/collection_detail.html'
    queryset= Collection.objects.all()




def create_collection(request):
    if not request.user.is_authenticated():
        return request(request,'bookmarks/login/login.html')
    else:
        form = CollectionForm(request.POST or None)


        if form.is_valid():
            collection=form.save(commit=False)
            collection.user= request.user
            collection.save()
            collection = Collection.objects.all()
            return render(request, 'bookmarks/collections.html', { 'collections': collection})

    context={
        'form': form
    }
    return render(request, 'bookmarks/create_collection.html',context)

class update_collection(UpdateView):
    model = Collection


class delete_collection(DeleteView):
    model = Collection

    success_url = reverse_lazy('bookmarks:collections')
    """
    Function based delete
    def delete_collection(request, collection_id):
    collection = Collection.objects.get(pk=album_id)
    collection.delete()
    collection = Collection.objects.filter(user=request.user)
    return render(request, 'bookmarks/index.html', {'collection':s collection})
    """
    """
    from django.http import Http404
    def get_object(self, queryset=None):
     #  Hook to ensure object is owned by request.user. 
        obj = super(collection_delete, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('bookmarks.views.details', args=[str(self.id)])
    """

def create_bookmarks(request, collection_id):
    if not request.user.is_authenticated():
        return render(request,'bookmarks/login/login.html')
    else:
        form = BookmarkForm(request.POST or None)
        collections =get_object_or_404(Collection, pk = collection_id )

        if form.is_valid():
            """
            Alternative to get object from user. 
            >>> user=request.user
            >>> collections_links= user.objects.get(id= collection_id)
            to
            >>> collections_links = User.objects.get(id= request.user.id)
            """
            """
                Manager isn't accessible via `Model` instances
                Solution:
                    Reverse related object lookup.

            """

            collections_links = collections.bookmarks_set.all()


            for s in collections_links:
                if s.name == form.cleaned_data.get('name'):
                    context={
                        'form': form,
                        'collections': collections,
                        'error_message': "Ops.. There's a title name similar to this. Please use other title to avoid conflict"

                    }
                    return render(request, 'bookmarks/create_bookmarks.html', context)
            links = form.save(commit=False)
            links.collection = collections
            #Match the Foreign Key
            links.save()
            return render(request, 'bookmarks/collection_detail.html', { 'collections': collections })

    context= {
        'collections': collections,
        'form': form

    }
    return render(request, 'bookmarks/create_bookmark.html', context)

class delete_bookmark(DeleteView):
    model = Bookmarks
    success_url = reverse_lazy('bookmarks:collections')


bookmarks/templates/bookmarks/login/login.html

{% extends 'bookmarks/base_visitor.html' %}

{% block body %}

<div class="container-fluid">

    <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Log In</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="{% url 'bookmarks:login_user'%}" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_username">
                                Username:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_username" maxlength="30" name="username" type="text">
                            </div>
                        </div>
                        <div class="form-group">
                            <label class="control-label col-sm-2" for="id_password">
                                Password:
                            </label>
                            <div class="col-sm-10">
                                <input id="id_password" maxlength="30" name="password" type="password">
                            </div>
                        </div>
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Don't have an account? <a href="{% url 'bookmarks:register' %}">Click here</a> to register.
                </div>
            </div>
        </div>
        
         <div class="col-sm-12 col-md-5">
            <div class="panel panel-default">
                <div class="panel-body">
                    <label for="username">Username: </label>
                    <label for="username">admin</label>
                </div>
            </div>
        </div>
        
    </div>

</div>

{% endblock %}

bookmarks/templates/bookmarks/login/register.html
{% extends 'bookmarks/base_visitor.html' %}

{% block body %}

<div class="container-fluid">
      <div class="row">
        <div class="col-sm-12 col-md-6">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Register for an Account</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'bookmarks/snipplets/form_template.html' %}

                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
                <div class="panel-footer">
                    Already have an account? <a href="{% url 'bookmarks:login_user' %}">Click here</a> to log in.
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}