MarkPro/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from bookmarks.views import (
    homeview,
    newsView,
    newsDetailView,
    newsListView,
)

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('bookmarks.urls', namespace="bookmarks")),

]

bookmarks/urls.py
from django.conf.urls import url
from .views import *

urlpatterns= [
    url(r'^$', homeview , name="index"),
    url(r'^login/$', loginView , name="login_user"),
    url(r'^logout_user/$', logoutView, name='logout_user'),
    url(r'^register/$', registerView , name="register"),

    #collections
    url(r'^collections/$', collectionView , name="collections"),
    url(r'^collections/create/$', create_collection, name="create_collections"),
    url(r'^collections/(?P<id>[\w-]+)/update/$', update_collection.as_view(), name="update_collections"),
    url(r'^collections/(?P<slug>[\w-]+)/delete/$', delete_collection.as_view(), name="delete_collection"),
    url(r'^collections/(?P<slug>[\w-]+)/$', collectionDetailView.as_view(), name="collection_detail"),


    #bookmarks
    url(r'^(?P<collection_id>[0-9]+)/create_bookmarks/$', create_bookmarks, name='create-bookmark'),
    url(r'^(?P<pk>[0-9]+)/delete_bookmark/$', delete_bookmark.as_view(),name="delete-bookmark"),
    #news
    url(r'^news/$',newsView, name="news"),
    # url(r'^news/$',newsListView.as_view(), name="news"),
    url(r'^news/(?P<slug>[\w-]+)/$', newsDetailView.as_view(), name="news_detail"),
    # url(r'^news/(?P<news>\w+)/$$',newsDetailView.as_view(), name="news"),

]

bookmarks/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import pre_save, post_save
from .utils import unique_slug_generator
from django.core.validators import URLValidator

from django.core.urlresolvers import reverse

def rl_pre_save_receiver(sender, instance, *args,**kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

class Newsboard(models.Model):
    title = models.CharField(max_length = 255)
    topic = models.CharField(max_length= 255)
    description = models.TextField()
    timestamp= models.DateTimeField(auto_now=False, auto_now_add=True)
    updated= models.DateTimeField(auto_now=True, auto_now_add=False)
    slug= models.SlugField(null=True, blank=True)
    def __str__(self):
        return self.title


pre_save.connect(rl_pre_save_receiver, sender=Newsboard)

class Collection(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    list_title=models.CharField(max_length=200)
    list_type=models.CharField(max_length=200)
    list_description=models.TextField()
    collection_logo = models.FileField(blank=True, null=True)
    timestamp= models.DateTimeField(auto_now=False, auto_now_add=True)
    updated= models.DateTimeField(auto_now=True, auto_now_add=False)
    slug = models.SlugField(null=True, blank=True)

    def __str__(self):
        return self.list_title
    # def __iter__(self):
    #     return iter(self._values)
        # return [field.value_to_string(self) for field in Collection._meta.fields]
    def get_absolute_url(self, *args, **kwargs):
        return reverse('bookmarks:collection_detail', kwargs={'pk': self.pk })


pre_save.connect(rl_pre_save_receiver, sender=Collection)

class Bookmarks(models.Model):

    collection =models.ForeignKey(Collection, on_delete=models.CASCADE)
    name = models.CharField(max_length=255)
    bookmarks_links= models.TextField(validators=[URLValidator()])
    bookmarks_description= models.TextField()

    def __str__(self):
        return self.name


"""
Add timestamp and modified time.
Source over here
https://stackoverflow.com/questions/1737017/django-auto-now-and-auto-now-add
---------------------------------------
I would recommend not using auto_now or auto_now_add and
instead define your own save() method to make sure that created is only updated if id is not set 
(such as when the item is first created), 
and have it update modified every time the item is saved.
from django.utils import timezone

class User(models.Model):
    created     = models.DateTimeField(editable=False)
    modified    = models.DateTimeField()

    def save(self, *args, **kwargs):
        ''' On save, update timestamps '''
        if not self.id:
            self.created = timezone.now()
        self.modified = timezone.now()
        return super(User, self).save(*args, **kwargs)

"""

bookmarks/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Collection, Newsboard, Bookmarks


class CollectionForm(forms.ModelForm):
    class Meta:
        model= Collection
        fields=['list_title', 'list_type', 'list_description']

class BookmarkForm(forms.ModelForm):
    class Meta:
        model= Bookmarks
        fields= ['name', 'bookmarks_links', 'bookmarks_description']

class NewsboardForm(forms.ModelForm):
    class Meta:
        model= Newsboard
        fields= '__all__'


class LoginForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)
    class Meta:
        model= User
        fields = ['username', 'password', 'email']



bookmarks/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth import logout, authenticate, login
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView,DeleteView, UpdateView
from django.db.models import Q
from django.urls import reverse_lazy
from .models import Newsboard, Collection, Bookmarks
from .forms import LoginForm, CollectionForm, NewsboardForm, BookmarkForm
from django.http import HttpResponseRedirect

def homeview(request):
    #HomeTemplateView
    if not request.user.is_authenticated():
        template_name = 'bookmarks/home_visitor.html'
    else:
        template_name = 'bookmarks/home.html'
    story = Newsboard.objects.all().order_by('-timestamp')
    context = {
        "newsboard": story
    }
    return render(request, template_name, context)

def newsView(request):
    template_name = "bookmarks/news.html"
    story = Newsboard.objects.all().order_by('-timestamp')
    context = {
        "newsboard": story
    }
    return render(request, template_name, context)

class newsListView(ListView):
    """
        Same as newsView(request)
        ListView to display news with filter

    """
    queryset= Newsboard.objects.all()
    template_name = "bookmarks/news.html"
    def get_queryset(self):
        slug = self.kwargs.get("slug")
        if slug:
            queryset=Newsboard.objects.filter(
                Q(topic__iexact=slug) |
                Q(topic__icontains=slug)
            )
        else:
            queryset=Newsboard.objects.all()
        return queryset

class newsDetailView(DetailView):

    queryset= Newsboard.objects.all()
    # def get_context_data(self, *args, **kwargs):
    #     print(self.kwargs)
    #     #get the id
    #     context= super(newsDetailView,self).get_context_data(*args, **kwargs)
    #     print(context)
    #     # it returns the object details
    #     return context

    # def get_object(self, *args, **kwargs):
    #     """
    #         This function is to change the urls.py as news_id
    #         pk  >  news_id
    #         url(r'^news/(?P<news_id>\w+)/$$', newsDetailView.as_view(), name="news"),
    #         if not will get AttributeError. Must be pk or slug.
    #         This function is not necessary if you stay as pk or slug.
    #     """
    #     news_id= self.kwargs.get('news_id')
    #     obj=get_object_or_404(Newsboard, id=news_id)
    #     return obj


def loginView(request):
    if request.method == "POST":
        username= request.POST['username']
        password= request.POST['password']
        user = authenticate(username=username, password=password)
        if user is not None:
            if user.is_active:
                login(request,user)
                if not request.user.is_authenticated():
                    template_name = 'bookmarks/home_visitor.html'
                else:
                    template_name = 'bookmarks/home.html'
                story = Newsboard.objects.all().order_by('-timestamp')
                context = {
                    "Newsboard": story
                }
                return render(request, template_name, context)

            else:
                return render(request, 'bookmarks/login/login.html',{'error_message': 'Your account has been disabled'})
        else:
            return render(request,'bookmarks/login/login.html', {'error_message': 'Invalid Login'})
    return render(request, 'bookmarks/login/login.html')

def logoutView(request):
    logout(request)
    form = LoginForm(request.POST or None)
    return render(request, 'bookmarks/login/login.html',{'form': form })

def registerView(request):
    form = LoginForm(request.POST or None)
    if form.is_valid():
        user = form.save(commit=False)
        username=form.cleaned_data['username']
        password=form.cleaned_data['password']
        user.set_password(password)
        user.save()
        user = authenticate(username=username, password=password)

        if user is not None:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect('/')
                #does not change url
                # return render(request, 'bookmarks/home.html', { 'user': request.user } )

    return render(request, 'bookmarks/login/register.html', {'form': form})



def collectionView(request):
    if not request.user.is_authenticated():
        return render(request, 'bookmarks/login/login.html')
    else:
        collections = Collection.objects.filter(user=request.user)
        return render(request, 'bookmarks/collections.html', {'collections': collections})

class collectionDetailView(DetailView):
    #default template name is myModelName_detail.html
    template_name = 'bookmarks/collection_detail.html'
    queryset= Collection.objects.all()




def create_collection(request):
    if not request.user.is_authenticated():
        return request(request,'bookmarks/login/login.html')
    else:
        form = CollectionForm(request.POST or None)


        if form.is_valid():
            collection=form.save(commit=False)
            collection.user= request.user
            collection.save()
            collection = Collection.objects.all()
            return render(request, 'bookmarks/collections.html', { 'collections': collection})

    context={
        'form': form
    }
    return render(request, 'bookmarks/create_collection.html',context)

class update_collection(UpdateView):
    model = Collection


class delete_collection(DeleteView):
    model = Collection

    success_url = reverse_lazy('bookmarks:collections')
    """
    Function based delete
    def delete_collection(request, collection_id):
    collection = Collection.objects.get(pk=album_id)
    collection.delete()
    collection = Collection.objects.filter(user=request.user)
    return render(request, 'bookmarks/index.html', {'collection':s collection})
    """
    """
    from django.http import Http404
    def get_object(self, queryset=None):
     #  Hook to ensure object is owned by request.user. 
        obj = super(collection_delete, self).get_object()
        if not obj.owner == self.request.user:
            raise Http404
        return obj

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('bookmarks.views.details', args=[str(self.id)])
    """

def create_bookmarks(request, collection_id):
    if not request.user.is_authenticated():
        return render(request,'bookmarks/login/login.html')
    else:
        form = BookmarkForm(request.POST or None)
        collections =get_object_or_404(Collection, pk = collection_id )

        if form.is_valid():
            """
            Alternative to get object from user. 
            >>> user=request.user
            >>> collections_links= user.objects.get(id= collection_id)
            to
            >>> collections_links = User.objects.get(id= request.user.id)
            """
            """
                Manager isn't accessible via `Model` instances
                Solution:
                    Reverse related object lookup.

            """

            collections_links = collections.bookmarks_set.all()


            for s in collections_links:
                if s.name == form.cleaned_data.get('name'):
                    context={
                        'form': form,
                        'collections': collections,
                        'error_message': "Ops.. There's a title name similar to this. Please use other title to avoid conflict"

                    }
                    return render(request, 'bookmarks/create_bookmarks.html', context)
            links = form.save(commit=False)
            links.collection = collections
            #Match the Foreign Key
            links.save()
            return render(request, 'bookmarks/collection_detail.html', { 'collections': collections })

    context= {
        'collections': collections,
        'form': form

    }
    return render(request, 'bookmarks/create_bookmark.html', context)

class delete_bookmark(DeleteView):
    model = Bookmarks
    success_url = reverse_lazy('bookmarks:collections')


bookmarks/templates/bookmarks/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
    <title>{%block title%} Home {% endblock%}</title>
</head>

<body>
<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">MarkPro </a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="#">About us</a></li>
        <li><a href="{% url 'bookmarks:collections' %}">Collections</a></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="{% url 'bookmarks:create_collections' %}"><span class="glyphicon glyphicon-plus"></span> Add Collection</a></li>
        <li><a href="#"><span class="glyphicon glyphicon-user"></span> Profile</a></li>
        <li><a href="{% url 'bookmarks:logout_user' %}"><span class="glyphicon glyphicon-log-out"></span> Log out </a></li>
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{%  endblock %}

<script src="{% static 'js/scrollReveal.js'%}"></script>
</body>
</html>

bookmarks/templates/bookmarks/base_visitor.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link href="https://fonts.googleapis.com/css?family=Poppins" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>

    <title>{%block title%} Home {% endblock%}</title>
</head>
<body>

<nav class="navbar navbar-custom">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>

      </button>
      <a class="navbar-brand" href="#">MarkPro</a>
    </div>
    <div class="collapse navbar-collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Home</a></li>
        <li><a href="#">About us</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">
          <li><a href="/register/"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
          <li><a href="{% url 'bookmarks:login_user' %}"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
      </ul>
    </div>
  </div>
</nav>

{% block body %}
{%  endblock %}

<script src="{% static 'js/scrollReveal.js'%}"></script>
</body>
</html>

bookmarks/templates/bookmarks/collection_detail.html
{% extends 'bookmarks/base.html' %}
{% block title %}Collections | Details {% endblock %}

{% block body %}
<div class="container">
     <!-- Left Collection Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h1>{{ object.list_title }}</h1>
                </div>
            </div>
        </div>

        <div class="col-sm-8 col-md-8">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'bookmarks:create-bookmark' collection.id %}">Add New Collection</a></li>
            </ul>
            <div class="panel panel-default">
                <div class="panel-body">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Links</th>
                                    <th>Copy</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    {% for bm in collection.bookmarks_set.all %}
                                        <tr>
                                            <td>{{ bm.name }}</td>
                                            <td><a href="{{ links.bookmarks_links }}" target="_blank">
                                                {{ bm.bookmarks_links }}
                                                </a>
                                            </td>
                                            <td><button class=" btn btn-info btn-xs">Copy</button></td>
                                            <td>
                                                <form action="{% url 'bookmarks:delete-bookmark' bm.id %}" method="post">
                                                    {% csrf_token %}
                                                    <input type="hidden" value="DELETE">
                                                    <button type="submit" class="btn btn-danger btn-xs">
                                                        <span class="glyphicon glyphicon-remove"></span>
                                                    </button>

                                                </form>
                                            </td>
                                        </tr>

                                    {% endfor %}
                                    <tr>
                                        <form class="form-horizontal" role="form" action="" method="post">
                                            {% csrf_token %}
                                            <td>
                                                 <input type="text" placeholder="Name">
                                             </td>
                                             <td>
                                                 <input type="text" placeholder="Name">
                                             </td>
                                             <td>
                                             </td>
                                             <td>
                                                 <button type="submit" class="btn btn-success btn-xs">
                                                        <span class="glyphicon glyphicon-plus"></span>
                                                 </button>
                                             </td>


                                        </form>
                                    </tr>

                                </tr>
                            </tbody>

                        </table>
                </div>
            </div>

        </div>

</div>


{% endblock %}

bookmarks/templates/bookmarks/collections.html
{% extends 'bookmarks/base.html' %}
{% block body %}

<div class="container">

    {% if collections %}
        {% for collection in collections %}
            <div class="col-sm-4 col-lg-2">
                    <div class="thumbnail">
                        <a href="{% url 'bookmarks:collection_detail' collection.slug %}">

                        </a>
                        <div class="caption">
                            <h2>{{ collection.list_title }}</h2>
                            <h4>{{ collection.list_type }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'bookmarks:collection_detail' collection.slug %}" class="btn btn-primary btn-sm" role="button">View Details</a>

                            <!-- Delete Collection -->
                            <form action="{% url 'bookmarks:delete_collection' collection.slug %}" method="post" style="display: inline;">
                                {% csrf_token %}
                                 <input type="hidden" name="collection_id" value="{{ collection.id }}" />
                                 <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>


                        </div>
                    </div>
                </div>

    {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
        {% endfor %}
    {% endif %}
</div>

{% endblock %}

bookmarks/templates/bookmarks/create_bookmark.html
{% extends 'bookmarks/base.html' %}
{% block title %}Add a New Bookmark{% endblock %}


{% block body %}
<div class="container-fluid">

    <div class="row">
        <div class="col-sm-8 col-md-9">

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Bookmark</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'bookmarks/snipplets/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}


bookmarks/templates/bookmarks/create_collection.html
 {% extends 'bookmarks/base.html' %}
{% block title %}Add a New Collection{% endblock %}

{% block body %}
<div class="container-fluid">

    <div class="row">

        <div class="col-sm-12 col-md-7">
            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Collection</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        {% include 'bookmarks/snipplets/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

bookmarks/templates/bookmarks/home.html
{% extends 'bookmarks/base.html' %}
{% block body %}

{% load static %}
<section id="showcase">
    <div class="container">
        <div class="bg-img">
        </div>
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="showcase-left">
                    <img src="{% static 'img/book.png' %}" alt="Book is missing.. Opsss!">
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="showcase-right">
                     <div class="jumbotron">
                        <h3>MarkPro blah blah blah</h3>
                        <p>Lorem ipsum dolor sit amet, consntur corate dus excepturi modi officia porro quia, quis repudianda</p>
                         <a href="#" class="btn btn-default showcase-btn btn-lg">Find out more</a>
                     </div>
                </div>

            </div>
        </div>
    </div>
</section>


<section id="news">

    {% for news in newsboard %}
        <h1>{{ news.title }}</h1>
        <small>{{ news.timestamp }}</small>
        <p> {{ news.description|slice:":10" }}
        ...
        <br>
        <span>Click here to <a href="/news/{{ news.slug }}">Read More</a> </span>
        <hr>
        </p>
    {% endfor %}
</section>

{% endblock %}

bookmarks/templates/bookmarks/home_visitor.html

{% extends 'bookmarks/base_visitor.html' %}

{% block body %}
{% load static %}
<section id="showcase">
    <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <div class="showcase-left">
                    <img src="{% static 'img/book.png' %}" alt="Book is missing.. Opsss!">
                </div>
            </div>
            <div class="col-md-6 col-sm-6">
                <div class="showcase-right">
                     <div class="jumbotron">
                        <h3>MarkPro is just for fun and it suits you!</h3>
                        <p>Lorem ipsum dolor sit amet, consntur corate dus excepturi modi officia porro quia, quis repudianda</p>
                         <a href="#" class="btn btn-default showcase-btn btn-lg">Find out more</a>
                     </div>
                </div>

            </div>
        </div>
    </div>
</section>
 {% for news in newsboard %}
            <h1>{{ news.title }}</h1>
            <small>{{news.timestamp }}</small>
            <p> {{ news.description|slice:":10" }}
                ...
                <br>
                <span>Click here to <a href="/news/{{ news.slug }}">Read More</a> </span>
                <hr>
            </p>
{% endfor %}


{% endblock %}

bookmarks/templates/bookmarks/news.html

{% extends 'bookmarks/base.html' %}

{% block body %}

<div class="container">

        {% for news in newsboard %}
            <h1>{{ news.title }}</h1>
            <small>{{news.timestamp }}</small>
            <p> {{ news.description }}</p>
        {% endfor %}

</div>

{% endblock %}

bookmarks/templates/bookmarks/newsboard_detail.html


<!--detailview  is used to make a page for one item-->

{% extends 'bookmarks/base.html' %}


{% block title%} News | {{ block.super }}{% endblock%}
{% block body %}

    <h1>{{ object.title }}</h1>
    <small>{{ object.timestamp }}</small>
    <p> {{ object.description }} | Updated {{ object.updated|timesince }} ago</p>

{% endblock %}